### ISSUE TITLE
[ver. 0.3.5] Invalid index

### ISSUE THREAD

**Issue by Suke0811** [qaz1678249/scalar_kinematics#7]
The example code fails with gripper =True.

```python
fk_res = my_scaler_k.scaler_forward_kinematics(which_leg, joint_angles, with_body=False, with_gripper = True, L_actuator=105, theta_actuator=0)
```

```
Traceback (most recent call last):
  File "C:/Users/TanakaYusuke/PycharmProjects/scalar_kinematics/scaler_kin/example.py", line 49, in <module>
    fk_res = my_scaler_k.scaler_forward_kinematics(which_leg, joint_angles, with_body=False, with_gripper = True, L_actuator=105, theta_actuator=0)
  File "C:\Users\TanakaYusuke\PycharmProjects\scalar_kinematics\scaler_kin\v3\SCALAR_kinematics.py", line 67, in scaler_forward_kinematics
    gripper_center_origin_toe_M, gripper_center_origin_toe_N = self.k_model.leg_gripper_fk(body_angle, joint_angles, L_actuator, theta_actuator, which_leg)
  File "C:\Users\TanakaYusuke\PycharmProjects\scalar_kinematics\scaler_kin\v3\SCALER_v2_Leg_6DOF_gripper.py", line 432, in leg_gripper_fk
    T_BC = np.array([[R_BC[0,0],R_BC[0,1],R_BC[0,2],x_pos[0]],
IndexError: invalid index to scalar variable.

Process finished with exit code 1
```

**Comment by qaz1678249** [comment]
This is an old issue related to python version, I think I fixed the same issue on the computer in the lab before.

**Comment by Suke0811** [comment]
You need to always push any big fix to the repository. If not pushed, it's
not fixed.
